apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: {{ .Values.backend.labels.app }}
spec:
  selector:
    app: {{ .Values.backend.labels.app }}

  ports:
  {{- with index .Values.backend.service.ports 0 }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
  
  type: {{ .Values.backend.service.type }}
