apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  database-user: {{ .Values.database.secrets.user | quote }}
  database-password: {{ .Values.database.secrets.password | quote }}