apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: {{ .Values.frontend.labels.app }}
  ports:
    - protocol: {{ index .Values.frontend.service.ports 0 "protocol" }}
      port: {{ index .Values.frontend.service.ports 0 "port" }}
      targetPort: {{ index .Values.frontend.service.ports 0 "targetPort" }}
  type: {{ .Values.frontend.service.type }}
